# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a4d4acc52e9ea4fed81de3c4fcad752e83841c4f4dc9d2040817fd9d891a7d14ba6ff021793b3a23acfecf0f8ec4474413bcf996db349436b666b5ad503d91b

test:
  secret_key_base: 1dc28f151bab2bb3108dbd54e0fb9f9b542a5094a2af6b8b0145f8f97dd5e83b22dd727f3d3e34591d8e30e2138ca48d0789ee71991abd56fae43ca5e6eeddd0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
